### PR TITLE
Uvc video support

### PR DESCRIPTION
**Pull request by RomanLut**
Support for ROTG01/ROTG02 receivers, with recording. There is a new button on toolbar to switch layout.

This is major change which includes all my other pull requests.

Please see building instructions:
https://github.com/RomanLut/android-taranis-smartport-telemetry/blob/master/doc/development.md

image

image

### CODE REVIEW

**Comment by CrazyDude1994** [comment]
hi. there are merge conflicts. Also I'm thinking about making this a separate APK and app on google play. I'm not decided about this though

**Comment by RomanLut** [comment]
Please provide your decision, then I will create pull request based on your master branch.
It would be prefferable to have single application to decrease maitenance costs.
If someone does not need UVC support, he does not have to use it. Just use layout with fullscreen map.

You can try a version with uvc support by compiling master branch:
https://github.com/RomanLut/android-taranis-smartport-telemetry
or precompiled apk:
https://github.com/RomanLut/android-taranis-smartport-telemetry/blob/uvc_video_upport/app-debug.apk


I had a 45 minute flight with inav plane yesterday and it worked very well.
image

**Comment by s2kaka** [comment]
Screenshot_2021-05-03-12-34-59-968_com miui bugreport
My xiao mi redmi 9 pro not work.
Can not see video and crash

**Comment by RomanLut** [comment]
> My xiao mi redmi 9 pro not work.
> Can not see video and crash

Does Go FPV app:
https://play.google.com/store/apps/details?id=com.vertile.fpv3d&hl=uk&gl=US
work on this phone?

**Comment by s2kaka** [comment]
Yes, it work. I use rotg01 pro.
Open app and try to open video on the left. Then app crash. Telemetry can’t load map too

**Comment by RomanLut** [comment]
Should be fixed (Android >9 requires Camera permission to access USB camera):
https://github.com/RomanLut/android-taranis-smartport-telemetry/blob/master/app-debug.apk

**Comment by ajjjjjjjj** [comment]
Tested on android 11 with rotg01 pro, works ok.
Are you planing publishing binary with recent changes?

**Comment by pan-sattan** [comment]
@RomanLut hi, I already tested your version... and its working well... but I cannot see rssi and rc channels values
Screenshot_20220224-130435_Telemetry viewer

**Comment by RomanLut** [comment]
@pan-sattan, 8 first rc channels are available with INav+Mavlink only.
RSSI is available with Frsky and Mavlink only.
What telemetry protocol are you using?

**Comment by pan-sattan** [comment]
@RomanLut I am using betaflight, but the code for rssi and rc channels should be the same... and frsky s.port

**Comment by pan-sattan** [comment]
I tested the same with Inav and the same behavior

**Comment by derFrickler** [comment]
Hi There, i just wanted to test the UVC Receiver support, but i can't get it to work. 
tested on 3 different Anfroid devices with a ROTG01 Pro and a simmilar Skydroid receiver. 
Both devides work in other Apps like Go FPV or OTG Cam, but as soon as i open Telemetry Viewer with the device connected, it does not show an image and crashes after some seconds. 

Any Hints? Would really like to get this working.

**Comment by pan-sattan** [comment]
> Hi There, i just wanted to test the UVC Receiver support, but i can't get it to work. tested on 3 different Anfroid devices with a ROTG01 Pro and a simmilar Skydroid receiver. Both devides work in other Apps like Go FPV or OTG Cam, but as soon as i open Telemetry Viewer with the device connected, it does not show an image and crashes after some seconds.
> 
> Any Hints? Would really like to get this working.

same for me

**Comment by RomanLut** [comment]
Closing due to newer PR https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/pull/154

**Pull request closed without merging**
